plugins {
    id 'java'
}

group = 'dev.lhoopy'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        url = 'https://repo.c7x.dev/repository/maven-public/'
        credentials {
            username = findProperty('c7xUsername') ?: System.getenv('C7X_USERNAME')
            password = findProperty('c7xPassword') ?: System.getenv('C7X_PASSWORD')
        }
    }
}

dependencies {
    implementation 'gg.cristalix:enginex:5.14.3'
}

jar {
    archiveFileName = 'BundleTest-bundle.jar'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    sourceCompatibility = '1.8'
    targetCompatibility = '1.8'
}
